---
title: "Machine learning paradigms and workflows"
author: 
  - name: Stephanie Hicks
    url: https://stephaniehicks.com
    affiliation: Department of Biostatistics, Johns Hopkins
    affiliation_url: https://publichealth.jhu.edu
description: "Overview of ML paradigms and workflows in R"
date: 2024-11-14
---


# Pre-lecture activities

::: callout-important

In advance of class, please

- TBA

:::

In addition, please read through

- TBA

::: callout-note

## How much should I prepare for before class? 

TBA

:::


# Lecture 

## Acknowledgements

Material for this lecture was borrowed and adopted from

- 

## Learning objectives

::: callout-note
### Learning objectives

**At the end of this lesson you will:**

-  State the differences between machine learning paradigms including supervised, unsupervised, semi-supervised, and reinforcement Learning
-  Describe when you might want to use different paradigms
-  Describe some common methods for each of the ML paradigms
-  Describe some evaluation techniques

:::



## Slides 

- Will be added here. <add here>

# Class activity 

For the rest of the time in class, you and your team will work on the final project. Stephanie will walk around to answer questions and to help in anyway I can. 


# Post-lecture

## Additional practice

Here are some additional practice questions to help you think about the material discussed.

::: callout-note
### Questions

1. TBA
:::