---
title: "Data Collection"
author: 
  - name: Stephanie Hicks
    url: https://stephaniehicks.com
    affiliation: Department of Biostatistics, Johns Hopkins
    affiliation_url: https://publichealth.jhu.edu
description: "add here"
date: 2024-11-07
draft: true
---

# Pre-lecture activities

::: callout-important

In advance of class, please install the following R packages

1. `jsonlite` (<https://jeroen.cran.dev/jsonlite>)
2. `httr` (<https://httr.r-lib.org>)

```{r}
#| eval: false
install.packages("jsonlite")
install.packages("httr")
```

:::

In addition, please read through

- [Data collection with APIs](../../readings/04-data-collection-apis/index.qmd)
- [Data collection from HTMLs](../../readings/04-data-collection-html/index.qmd)

::: callout-note

## How much should I prepare for before class? 

:::


# Lecture 

## Acknowledgements

Material for this lecture was borrowed and adopted from

- <https://jhu-advdatasci.github.io/2019/lectures/04-gettingdata-api.html>
- <https://aws.amazon.com/what-is/api>
- <https://bookdown.org/paul/apis_for_social_scientists/github.com-api.html>
- <https://statisticsglobe.com/api-in-r>


## Learning objectives

::: callout-note
### Learning objectives

**At the end of this lesson you will:**

- Describe what the difference is between "raw" vs "clean" data
- Learn about what are JSON files and how we can convert them into data frames in R 
- Describe some best practices on sharing data with collaborators
- Know what does API mean and state four types of API architectures
- Practice with two APIs: the GitHub API and the openFDA API

:::


## Slides 

- <add here>


# Post-lecture

## Other good R packages to know about 

- [googlesheets4](https://cran.r-project.org/web/packages/googlesheets4/index.html) to interact with Google Sheets in R
- [googledrive](https://googledrive.tidyverse.org/) to interact with files on your Google Drive


## Summary 

- 

## Additional practice

Here are some additional practice questions to help you think about the material discussed.

::: callout-note
### Questions

1. 1.  Using the GitHub API, access the repository information and ask how many open github issues you have?
2. Pick another API that we have not discussed here and use `httr` to retreive data from it. 
:::