---
title: "Database programming paradigms"
author: 
  - name: Stephanie Hicks
    url: https://stephaniehicks.com
    affiliation: Department of Biostatistics, Johns Hopkins
    affiliation_url: https://publichealth.jhu.edu
description: "Relational databases and SQL basics"
date: 2024-11-12
---

# Pre-lecture activities

::: callout-important

For this lecture, we will use Unix shell, plus [SQLite3](https://www.sqlite.org/index.html) or [DB Browser for SQLite](https://sqlitebrowser.org).

You can see if the command-line tool `sqlite3` (also known as "SQLite") is already installed with 

```{bash}
sqlite3 --version
```

If not, you can install with `homebrew` or follow the instructions here: 

- <https://swcarpentry.github.io/sql-novice-survey/setup.html>

Also, you will need to install these R packages:

```{r}
#| eval: false
install.packages("DBI")
install.packages("RSQLite")
install.packages("dbplyr")
```

:::

In addition, please read through

- [Relational databases and SQL basics](../../readings/05-database-programming/index.qmd)
- <https://swcarpentry.github.io/sql-novice-survey>


::: callout-note

## How much should I prepare for before class? 

Please install the packages above and be comfortable with running the functions in the example code: 

- <https://dbi.r-dbi.org>
- <https://solutions.posit.co/connections/db/databases/sqlite/>
- <https://dbplyr.tidyverse.org>

:::


# Lecture 

## Acknowledgements

Material for this lecture was borrowed and adopted from

- <https://www.stephaniehicks.com/jhuads2021/posts/2021-12-06-sql-basics>
- <https://swcarpentry.github.io/sql-novice-survey>


## Learning objectives

::: callout-note
### Learning objectives

**At the end of this lesson you will:**

- Explain the difference between a table, a record, and a field in relational databases
- Explain the difference between a database and a database manager
- Write a query to select all values for specific fields from a single table
- Write queries that display results in a particular order
- Write queries that eliminate duplicate values from data
- Write queries that select records that satisfy user-specified conditions
- Learn about the `DBI`, `RSQLite`, `dbplyr` packages for making SQL queries in R

:::



## Slides 

- <add here>

# Class activity 

For the rest of the time in class, we will practice playing with SQL databases.

::: callout-note
### Objectives of the activity

- TBA   

:::

For this in-class activity, you need to find a partner. 

# Post-lecture

## Additional practice

Here are some additional practice questions to help you think about the material discussed.

::: callout-note
### Questions

Using the `survey.db` database: 

1. Use `.schema` to identify column that contains integers
2. Write a query that selects only the `name` column from the `Site` table.
3. Many people format queries in the following two ways. What style do you find easiest to read, and why?

```
SELECT personal, family FROM person;
```

or

```
select Personal, Family from PERSON;
```

4. Write a query that selects distinct dates from the `Visited` table.
5. Write a query that displays the full names of the scientists in the `Person` table, ordered by family name.

:::