---
title: "R package development and pkgdown"
author: 
  - name: Stephanie Hicks
    url: https://stephaniehicks.com
    affiliation: Department of Biostatistics, Johns Hopkins
    affiliation_url: https://publichealth.jhu.edu
description: "Introduction to building and documenting R packages"
date: 2024-11-26
---

# Pre-lecture activities

::: callout-important

In advance of class, please install two additional packages:

* `devtools` - this provides many additional tools for building packages
* `roxygen2` - this provides tools for writing documentation
* `pkgdown`  - this helps you to build a package website with little effort
* `usethis`  - an automation package that simplifies project creation and setup

You can do this by calling

```{r}
#| eval: false
install.packages(c("devtools", "roxygen2",
                   "usethis", "pkgdown"))
```

In addition, please read through: 

- <https://r-pkgs.org>
- <https://stat545.com/package-overview>
- <https://usethis.r-lib.org>
- <https://pkgdown.r-lib.org/articles/pkgdown>

:::



# Lecture 

## Acknowledgements

Material for this lecture was borrowed and adopted from

- <https://pkgdown.r-lib.org/index.html>
- <https://bookdown.org/yihui/rmarkdown/pkgdown-components.html>


## Learning objectives

::: callout-note
### Learning objectives

**At the end of this lesson you will:**
 
- Create an empty R package 
- Design a R function and write documentation
- Describe what a `DESCRIPTION` file is and what goes in it
- Be able to build and install a R package
- Build a website for your package

:::


## Slides 

- [Lecture 09: R package development](https://docs.google.com/presentation/d/1Gr2SOWrm7hnbFR1CzNIlREXeNLYD2H-msYpogO-_f0A/edit?usp=sharing)

